#!/data/data/com.termux/files/usr/bin/bash

echo "https://github.com/offici5l/MiTool"
current_version=$(cat "$PREFIX/bin/mitoolV" | awk -F '(' '{print $2}' | awk -F ')' '{print $1}')
latest_version=$(curl -s https://raw.githubusercontent.com/offici5l/MiTool/master/mitoolV | awk -F '(' '{print $2}' | awk -F ')' '{print $1}')
printf "\e[1;32mVersion [current:%s | latest:%s]\e[0m\n" "$current_version" "$latest_version"

if [ "$(printf "$current_version\n$latest_version" | sort -V | tail -n 1)" != "$current_version" ]; then
    echo "
(type u to update or Enter to skip..)"
    read -p "new update available! update MiTool ? : " update
    if [ "$update" == "u" ]; then
        curl https://raw.githubusercontent.com/offici5l/MiTool/master/install.sh | bash
        exit
    else
        echo "skip update .."
    fi
else
    echo
fi

echo
echo "1. Flash-Fastboot-ROM"
echo "2. Flash-Recovery-ROM"
echo "3. Unlock-Bootloader"
echo "4. Root"

read -p "
Enter your choice (1/2/3/4): " choice

if [ "$choice" == "1" ]; then
    python3 "$PREFIX/bin/flashfastbootrom.py"
elif [ "$choice" == "2" ]; then
    python3 "$PREFIX/bin/flashrecoveryrom.py"
elif [ "$choice" == "3" ]; then
    python3 "$PREFIX/bin/unlockbootloader.py"
elif [ "$choice" == "4" ]; then
    python3 "$PREFIX/bin/root.py"
else
    echo "
Invalid choice
"
fi